# Generated by Django 6.0.2 on 2026-02-10 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spinhistory',
            name='option',
        ),
        migrations.AddField(
            model_name='spinhistory',
            name='options_snapshot',
            field=models.TextField(default=datetime.datetime(2026, 2, 10, 13, 45, 19, 303361, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spinhistory',
            name='result',
            field=models.CharField(default=datetime.datetime(2026, 2, 10, 13, 45, 25, 164790, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
